import { describe, expect, it } from 'vitest'
import { zodSchema } from 'ai'
import {
  coerceValue,
  columnSpec,
  insertStatement,
  planSeedColumns,
  seedRowsSchema
} from '../../../src/main/ai/generate-seed'
import type { ColumnInfo, TableDetails } from '../../../src/shared/types'

function col(overrides: Partial<ColumnInfo> = {}): ColumnInfo {
  return {
    name: 'action',
    dataType: 'USER-DEFINED',
    udtName: 'audit_action',
    isNullable: false,
    isPrimaryKey: false,
    defaultValue: null,
    ordinalPosition: 1,
    characterMaximumLength: null,
    enumValues: ['Update', 'Login', 'Status Change'],
    ...overrides
  }
}

function details(columns: ColumnInfo[]): TableDetails {
  return {
    schema: 'public',
    name: 'audit_logs',
    type: 'table',
    columns,
    primaryKey: [],
    indexes: [],
    foreignKeys: [],
    estimatedRows: 0
  }
}

describe('the column list the model is asked to fill', () => {
  it('names the enum type and its values', () => {
    // "USER-DEFINED (NOT NULL)" gave the model no way to invent an acceptable
    // value, so it returned no rows at all.
    const spec = columnSpec(details([col()]), [col()])

    expect(spec).toContain('action: audit_action (NOT NULL)')
    expect(spec).toContain("values: 'Update' | 'Login' | 'Status Change'")
    expect(spec).not.toContain('USER-DEFINED')
  })

  it('omits the length on a MySQL enum', () => {
    // MySQL reports an ENUM's characterMaximumLength as its longest label, so
    // "enum(12)" beside the real values only invites the model to truncate them.
    const mysql = col({
      dataType: "enum('Update','Login')",
      udtName: 'enum',
      characterMaximumLength: 12
    })

    expect(columnSpec(details([mysql]), [mysql])).toContain('- action: enum (NOT NULL)')
  })

  it('leaves an ordinary column rendering as it was', () => {
    const name = col({
      name: 'user_name',
      dataType: 'character varying',
      udtName: 'varchar',
      characterMaximumLength: 120,
      isNullable: true,
      enumValues: null
    })

    expect(columnSpec(details([name]), [name])).toContain(
      '- user_name: character varying(120) (nullable)'
    )
  })
})

/** The keys of the row object inside `{ rows: [...] }`, as the model is sent them. */
function rowSchema(columns: ColumnInfo[]): Record<string, unknown> {
  const json = zodSchema(seedRowsSchema(columns)).jsonSchema as Record<string, never>
  return (json.properties as never)['rows']['items'] as Record<string, unknown>
}

describe('which columns the model is asked to fill', () => {
  const noFk = new Set<string>()
  const title = col({ name: 'title', dataType: 'text', udtName: 'text', enumValues: null })
  const fillNames = (columns: ColumnInfo[]): string[] =>
    planSeedColumns(columns, noFk).fillColumns.map((c) => c.name)
  const schemaKeys = (columns: ColumnInfo[]): string[] =>
    Object.keys(rowSchema(planSeedColumns(columns, noFk).fillColumns).properties as object)

  it('leaves a MySQL auto_increment key to the database', () => {
    // auto_increment lives in information_schema's `extra`, never in
    // column_default, so the default-expression check never saw it: the model
    // invented ids and INSERT IGNORE dropped every duplicate as "Added 0 rows".
    const id = col({
      name: 'id',
      dataType: 'int',
      udtName: 'int4',
      isPrimaryKey: true,
      enumValues: null,
      isAutoGenerated: true
    })

    expect(fillNames([id, title])).toEqual(['title'])
    expect(schemaKeys([id, title])).toEqual(['title'])
  })

  it('leaves a Postgres identity column to the database', () => {
    // GENERATED ALWAYS AS IDENTITY has no column_default either, and rejects
    // every row that supplies a value.
    const id = col({
      name: 'id',
      dataType: 'integer',
      udtName: 'int4',
      isPrimaryKey: true,
      enumValues: null,
      isAutoGenerated: true
    })

    expect(fillNames([id, title])).toEqual(['title'])
    expect(schemaKeys([id, title])).toEqual(['title'])
  })

  it('leaves a D1 INTEGER PRIMARY KEY to the database', () => {
    // SQLite aliases it to the rowid; INSERT OR IGNORE dropped the invented ids.
    const id = col({
      name: 'id',
      dataType: 'INTEGER',
      udtName: 'int4',
      isPrimaryKey: true,
      enumValues: null,
      isAutoGenerated: true
    })

    expect(fillNames([id, title])).toEqual(['title'])
    expect(schemaKeys([id, title])).toEqual(['title'])
  })

  it('still recognises a serial by its default expression', () => {
    const id = col({
      name: 'id',
      dataType: 'integer',
      udtName: 'int4',
      isPrimaryKey: true,
      enumValues: null,
      defaultValue: "nextval('users_id_seq'::regclass)"
    })

    expect(fillNames([id, title])).toEqual(['title'])
  })

  it('still asks for a plain integer key the database will not supply', () => {
    const id = col({
      name: 'id',
      dataType: 'integer',
      udtName: 'int4',
      isPrimaryKey: true,
      enumValues: null
    })

    expect(fillNames([id, title])).toEqual(['id', 'title'])
  })

  it('does not mint a UUID for a generated string key', () => {
    const code = col({
      name: 'code',
      dataType: 'text',
      udtName: 'text',
      isPrimaryKey: true,
      enumValues: null,
      isAutoGenerated: true
    })

    const plan = planSeedColumns([code, title], noFk)
    expect(plan.generatedIdColumns).toEqual([])
    expect(plan.fillColumns.map((c) => c.name)).toEqual(['title'])
  })
})

describe('the response schema sent to the model', () => {
  const columns = [col(), col({ name: 'user_name', udtName: 'text', enumValues: null })]

  it('names every column it is asking for', () => {
    // A z.record converts to {type:'object', additionalProperties:{}} - a row
    // declaring no permitted keys. Sent as a native output_config.format the model
    // answers with an empty array, which surfaced as "returned no sample rows".
    const row = rowSchema(columns)

    expect(Object.keys(row.properties as object)).toEqual(['action', 'user_name'])
    expect(row.required).toEqual(['action', 'user_name'])
    expect(row.additionalProperties, 'an open row is what broke seeding').toBe(false)
  })

  it('accepts the JSON scalars a row value can be', () => {
    const parsed = seedRowsSchema(columns).safeParse({
      rows: [{ action: 'Update', user_name: null }]
    })
    expect(parsed.success).toBe(true)
  })

  it('rejects a row missing a column', () => {
    const parsed = seedRowsSchema(columns).safeParse({ rows: [{ action: 'Update' }] })
    expect(parsed.success).toBe(false)
  })
})

describe('coercing a model value for insertion', () => {
  it('repairs the case of an enum value', () => {
    expect(coerceValue(col(), 'update')).toBe('Update')
  })

  it('repairs punctuation and spacing', () => {
    expect(coerceValue(col(), 'status_change')).toBe('Status Change')
  })

  it('substitutes a real label when nothing matches a NOT NULL enum', () => {
    // Fabricated data either way - a usable row beats an insert certain to fail.
    expect(coerceValue(col(), 'Banana')).toBe('Update')
  })

  it('prefers null for an unmatched nullable enum', () => {
    expect(coerceValue(col({ isNullable: true }), 'Banana')).toBeNull()
  })

  it('does not treat an enum named like a date as a date', () => {
    // The type regexes match on the name: "update_time" hits /date|time/ and the
    // value would have been parsed as a timestamp and dropped.
    const timeish = col({ udtName: 'update_time', enumValues: ['Draft', 'Sent'] })

    expect(coerceValue(timeish, 'draft')).toBe('Draft')
  })

  it('still coerces non-enum types as before', () => {
    const int = col({ dataType: 'integer', udtName: 'int4', enumValues: null })
    const bool = col({ dataType: 'boolean', udtName: 'bool', enumValues: null })

    expect(coerceValue(int, '1,200')).toBe(1200)
    expect(coerceValue(bool, 'yes')).toBe(true)
    expect(coerceValue(int, null)).toBeNull()
  })

  it('reads a MySQL tinyint(1) as a boolean, not an integer', () => {
    // Its type string is "tinyint(1) bool" and the integer branch ran first:
    // Number('true') is NaN, so every NOT NULL boolean inserted as NULL and the
    // consecutive-failure cap ended the seed.
    const flag = col({ dataType: 'tinyint(1)', udtName: 'bool', enumValues: null })

    expect(coerceValue(flag, true)).toBe(true)
    expect(coerceValue(flag, 'no')).toBe(false)
  })

  it('passes an interval through as text', () => {
    // "interval" matched a bare /int/ and went through Number().
    const span = col({ dataType: 'interval', udtName: 'interval', enumValues: null })

    expect(coerceValue(span, '3 days')).toBe('3 days')
  })

  it('still truncates the integer family', () => {
    const big = col({ dataType: 'bigint', udtName: 'int8', enumValues: null })
    const tiny = col({ dataType: 'tinyint(4)', udtName: 'int4', enumValues: null })

    expect(coerceValue(big, '12.9')).toBe(12)
    expect(coerceValue(tiny, 3.7)).toBe(3)
  })
})

describe('the insert each row becomes', () => {
  // Quoting now comes from each engine's own dialect; these pin that the SQL
  // is unchanged for it.
  const cells = [
    { column: 'name', value: 'Ann' },
    { column: 'active', value: true }
  ]

  it("quotes through each engine's own dialect", () => {
    expect(insertStatement('postgres', 'public', 'users', cells)).toBe(
      `INSERT INTO "public"."users" ("name", "active") VALUES ('Ann', TRUE) ON CONFLICT DO NOTHING`
    )
    expect(insertStatement('mysql', 'app', 'users', cells)).toBe(
      "INSERT IGNORE INTO `app`.`users` (`name`, `active`) VALUES ('Ann', 1)"
    )
    expect(insertStatement('d1', 'main', 'users', cells)).toBe(
      `INSERT OR IGNORE INTO "users" ("name", "active") VALUES ('Ann', 1)`
    )
  })

  it('escapes a quote inside an identifier', () => {
    expect(insertStatement('postgres', 'public', 'we"ird', [{ column: 'a"b', value: 1 }])).toBe(
      `INSERT INTO "public"."we""ird" ("a""b") VALUES (1) ON CONFLICT DO NOTHING`
    )
    expect(insertStatement('mysql', 'app', 'we`ird', [{ column: 'a`b', value: 1 }])).toBe(
      'INSERT IGNORE INTO `app`.`we``ird` (`a``b`) VALUES (1)'
    )
  })

  it('escapes a backslash only where the engine reads it as one', () => {
    const path = [{ column: 'p', value: 'C:\\tmp' }]

    expect(insertStatement('mysql', 'app', 't', path)).toContain("'C:\\\\tmp'")
    expect(insertStatement('postgres', 'public', 't', path)).toContain("'C:\\tmp'")
  })

  it("inserts defaults when every column is the database's to fill", () => {
    expect(insertStatement('postgres', 'public', 'users', [])).toBe(
      'INSERT INTO "public"."users" DEFAULT VALUES ON CONFLICT DO NOTHING'
    )
    expect(insertStatement('mysql', 'app', 'users', [])).toBe(
      'INSERT IGNORE INTO `app`.`users` () VALUES ()'
    )
    expect(insertStatement('d1', 'main', 'users', [])).toBe(
      'INSERT OR IGNORE INTO "users" DEFAULT VALUES'
    )
  })
})
